name: dartssh
version: 1.0.4+4
description: Dart SSH package providing First-class tunnelling primitives.
author: Green Appers, Inc. <greenappers@gmail.com>
homepage: https://github.com/GreenAppers/dartssh

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asn1lib: ^1.0.2
  convert: ^3.0.1
  meta: ^1.7.0
  http: ^0.13.3
  pedantic: ^1.11.1
  pointycastle: ^3.3.1
  #tweetnacl:
    #git:
      #url: https://github.com/TerminalStudio/tweetnacl-dart
  tweetnacl:
    path:
      ../tweetnacl-dart

  validators: ^3.0.0

dev_dependencies:
  build_runner: 
  test: 
